### PR TITLE
fix start/stop preview

### PR DESCRIPTION
**Pull request by constambeys**

### CODE REVIEW

**Comment by pedroSG94** [comment]
Hello,

Can you tell me the reason to change it?
This changes provide side effects that I don't like in Camera1Base. For example in stopPreview, if you call is while streaming/recording the camera will be stoppped.

**Comment by constambeys** [comment]
Hi,

I liked your project, is very good, and I use it with some modifications to monitor my house from a mobile device.

However the last time I used it the phone was getting very hot because it was processing the camera feed continuously.

So I call stopPreview and startPreview every time I connect/disconnect but these methods did not work, so I made this change !

I think this change is logical because the only variable that changes in these methods is the onPreview.
 
Thanks
Timotheos Constambeys

**Comment by pedroSG94** [comment]
I see but this change the backwards compatibility so I think that the best idea is create a new method for it.

**Comment by pedroSG94** [comment]
Hello,

I fixed it. To allow this feature I added the method stopCamera. 
stopCamera method is the same that stopPreview but allow do it while streaming/recording
stopPreview keep the same functionality for backwards compatibility

**Pull request merged**
